package main

import (
    "github.com/gin-gonic/gin"
    "Go-Gin-practice/apis"
    "Go-Gin-practice/initialize"
    "Go-Gin-practice/global"
    swaggerFiles "github.com/swaggo/files"
    ginSwagger "github.com/swaggo/gin-swagger"
    _ "Go-Gin-practice/docs" // docs is generated by Swag CLI, you have to import it.
)


// @title Swagger Example API
// @version 1.0
// @host localhost:8080
// @BasePath /api/v1/
func main() {

    initialize.DBTables()
    defer global.GVA_DB.Close()

    router := gin.Default()
    api_v1 := router.Group("/api/v1")
    {
        download := api_v1.Group("/download")
        {
            download.GET("/:name", v1.Test)
            download.POST("/", v1.DownloadURL)
        }
    }
    url := ginSwagger.URL("http://localhost:8080/swagger/doc.json") // The url pointing to API definition
    router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))
    router.Run(":8080")
}
