package main

import (
    "fmt"
    "io/ioutil"
    "net/http"
    "github.com/gin-gonic/gin"

    swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
    _ "github.com/ZoeLiao/Go-Gin-practice/docs" // docs is generated by Swag CLI, you have to import it.
)

type URL struct {
    URL string `json:"url" form:"url"`
}

// Test example
// @Description test
// @name test name 
// @Accept  json
// @Produce  json
// @Param message body main.URL true "url"
// @Success 200 {string} string	"ok"
// @Router /download [post]
func DownloadURL(c *gin.Context) {
    var URL URL
    c.BindJSON(&URL)
    url := URL.URL
    resp, err := http.Get(url)
    if err != nil {
        fmt.Errorf("Error: %s", err)
        c.JSON(
            http.StatusOK,
            gin.H{"message": err},
        )
    } else {
        defer resp.Body.Close()
        body, err := ioutil.ReadAll(resp.Body)
        if err != nil {
            fmt.Errorf("Error: %s", err)
            c.JSON(
                http.StatusOK,
                gin.H{"message": err},
            )
        } else {
            fmt.Printf("found: %s %q\n", url, body)
            c.JSON(
                http.StatusOK,
                gin.H{"message": body},
            )
        }
    }
}

// Test example
// @Description test
// @name test name 
// @Accept  json
// @Produce  json
// @Param   name     path    string     true        "name"
// @Success 200 {string} string	"ok"
// @Router /download/{name} [get]
func Test(c *gin.Context) {
    name := c.Param("name")
    c.JSON(
        http.StatusOK,
        gin.H{"message": name},
    )
}

// @title Swagger Example API
// @version 1.0
// @host localhost:8080
// @BasePath /api/v1/
func main() {
    router := gin.Default()
    v1 := router.Group("/api/v1")
    {
        download := v1.Group("/download")
        {
            download.GET("/:name", Test)
            download.POST("/", DownloadURL)
        }
    }
    url := ginSwagger.URL("http://localhost:8080/swagger/doc.json") // The url pointing to API definition
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))
    router.Run(":8080")
}
