package router

import (
	"Go-Gin-practice/apis"
	_ "Go-Gin-practice/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func SetupRouter() *gin.Engine {
	router := gin.Default()
	api_v1 := router.Group("/api/v1")
	{
		shortener := api_v1.Group("/shortener")
		{
			shortener.GET("/:path", v1.GetURL)
			shortener.POST("", v1.CreateURL)
			shortener.PATCH("", v1.UpdateURL)
			shortener.DELETE("", v1.DeleteURL)
		}
		shorteners := api_v1.Group("/shorteners")
		{
			shorteners.GET("", v1.GetURLList)
		}
	}
	url := ginSwagger.URL("http://localhost:8080/swagger/doc.json") // The url pointing to API definition
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	// 404
	router.NoRoute(func(c *gin.Context) {
		c.JSON(
			404,
			gin.H{"message": "Oops! Page not found"})
	})
	return router
}
