package main

import (
	"Go-Gin-practice/backend/core"
	_ "Go-Gin-practice/backend/docs" // docs is generated by Swag CLI, you have to import it.
	"Go-Gin-practice/backend/initialize"
	"Go-Gin-practice/backend/router"
)

func init_db() {
	initialize.DBTables()
	core.Init()
}

// @title Swagger Example API
// @version 1.0
// @host localhost:8080
// @BasePath /api/v1/
func main() {
	init_db()
	r := router.SetupRouter()
	r.Run(":8080")
}
